import './global.css';

import type { Metadata } from 'next';
import { FC, PropsWithChildren } from 'react';

import { ToastContext } from '@/components/contexts/toast';

export const metadata: Metadata = {
  title: 'Family tree',
  description: 'Generated by create next app',
};

const RootLayout: FC<PropsWithChildren> = ({ children }) => {
  return (
    <html lang="en">
      <body>
        <ToastContext />
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
