import './global.css';

import type { Metadata } from 'next';

import { LayoutProps } from '@/types/layout';

export const metadata: Metadata = {
  title: 'Family tree',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: LayoutProps) => {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
};

export default RootLayout;
